spring.data.mongodb.uri=mongodb+srv://virat:virat18@cluster0.li14h5q.mongodb.net/snippetdb
# JWT Configuration
# Make sure to change this to a secure random string in production!
jwt.secret=7A24432646294A404E635266556A586E3272357538782F413F4428472B4B6250
jwt.expiration=86400000

# Server Config
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
